language: ruby
cache: bundler
rvm:
  - &latest_ruby 2.7
  - 2.5
env:
  - JEKYLL_VERSION="~> 3.9"
matrix:
  include:
    - # GitHub Pages
      rvm: 2.5.3
      env: GH_PAGES=true
    - rvm: *latest_ruby
      env: JEKYLL_VERSION="~> 4.0"

before_install:
- gem update --system
before_script: bundle update
script: script/cibuild
