language: ruby
before_script: bundle update
script: "script/cibuild"
sudo: false
cache: bundler

matrix:
  include:
    - # GitHub Pages
      rvm: 2.1.1
      env: GH_PAGES=true
  allow_failures:
    - env: GH_PAGES=true # Jekyll 2.4 will fail tests
  fast_finish: true

rvm:
  - 2.2
  - 2.1
  - 2.0
env:
  - ""
  - JEKYLL_VERSION=3.0
  - JEKYLL_VERSION=2.0
